export enum ApartmentType {
  APARTMENT_GET_LIST_REQUEST = 'apartment/APARTMENT_GET_LIST_REQUEST',
  APARTMENT_GET_LIST_SUCCESS = 'apartment/APARTMENT_GET_LIST_SUCCESS',
  APARTMENT_GET_LIST_FAILURE = 'apartment/APARTMENT_GET_LIST_FAILURE',

  APARTMENT_SET_FORM_FIELD = 'apartment/APARTMENT_SET_FORM_FIELD',
  APARTMENT_SET_FORM_FIELD_ERROR = 'apartment/APARTMENT_SET_FORM_FIELD_ERROR',
  APARTMENT_CLEAR_FORM_FIELD = 'apartment/APARTMENT_CLEAR_FORM_FIELD',
  APARTMENT_POPULATE_FORM_FIELD = 'apartment/APARTMENT_POPULATE_FORM_FIELD',

  APARTMENT_SUBMIT_FORM_REQUEST = 'apartment/APARTMENT_SUBMIT_FORM_REQUEST',
  APARTMENT_SUBMIT_FORM_SUCCESS = 'apartment/APARTMENT_SUBMIT_FORM_SUCCESS',
  APARTMENT_SUBMIT_FORM_FAILURE = 'apartment/APARTMENT_SUBMIT_FORM_FAILURE',

  APARTMENT_UPDATE_REQUEST = 'apartment/APARTMENT_UPDATE_REQUEST',
  APARTMENT_UPDATE_SUCCESS = 'apartment/APARTMENT_UPDATE_SUCCESS',
  APARTMENT_UPDATE_FAILURE = 'apartment/APARTMENT_UPDATE_FAILURE',

  APARTMENT_REMOVE_REQUEST = 'apartment/APARTMENT_REMOVE_REQUEST',
  APARTMENT_REMOVE_SUCCESS = 'apartment/APARTMENT_REMOVE_SUCCESS',
  APARTMENT_REMOVE_FAILURE = 'apartment/APARTMENT_REMOVE_FAILURE',

  APARTMENT_SET_FILTER = 'apartment/APARTMENT_SET_FILTER',
  APARTMENT_SET_DIALOG_OPEN_STATUS = 'apartment/APARTMENT_SET_DIALOG_OPEN_STATUS',
};
