export enum AuthType {
  AUTH_LOGIN_REQUEST = 'auth/AUTH_LOGIN_REQUEST',
  AUTH_LOGIN_SUCCESS = 'auth/AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILURE = 'auth/AUTH_LOGIN_FAILURE',
  AUTH_LOGIN_SET_FORM = 'auth/AUTH_LOGIN_SET_FORM',
  AUTH_LOGIN_SET_FORM_ERROR = 'auth/AUTH_LOGIN_SET_FORM_ERROR',
  AUTH_GET_CURRENT_USER_SUCCESS = 'auth/AUTH_GET_CURRENT_USER_SUCCESS',

  AUTH_REGISTER_REQUEST = 'auth/AUTH_REGISTER_REQUEST',
  AUTH_REGISTER_SUCCESS = 'auth/AUTH_REGISTER_SUCCESS',
  AUTH_REGISTER_FAILURE = 'auth/AUTH_REGISTER_FAILURE',
  AUTH_REGISTER_SET_FORM = 'auth/AUTH_REGISTER_SET_FORM',
  AUTH_REGISTER_SET_FORM_ERROR = 'auth/AUTH_REGISTER_SET_FORM_ERROR',

  AUTH_LOGOUT = 'auth/AUTH_LOGOUT',
}