export enum UsersType {
  USERS_GET_LIST_REQUEST = 'users/USERS_GET_LIST_REQUEST',
  USERS_GET_LIST_SUCCESS = 'users/USERS_GET_LIST_SUCCESS',
  USERS_GET_LIST_FAILURE = 'users/USERS_GET_LIST_FAILURE',

  USERS_SET_FORM_FIELD = 'users/USERS_SET_FORM_FIELD',
  USERS_SET_FORM_FIELD_ERROR = 'users/USERS_SET_FORM_FIELD_ERROR',
  USERS_CLEAR_FORM_FIELD = 'users/USERS_CLEAR_FORM_FIELD',
  USERS_POPULATE_FORM_FIELD = 'users/USERS_POPULATE_FORM_FIELD',

  USERS_SUBMIT_FORM_REQUEST = 'users/USERS_SUBMIT_FORM_REQUEST',
  USERS_SUBMIT_FORM_SUCCESS = 'users/USERS_SUBMIT_FORM_SUCCESS',
  USERS_SUBMIT_FORM_FAILURE = 'users/USERS_SUBMIT_FORM_FAILURE',

  USERS_UPDATE_REQUEST = 'users/USERS_UPDATE_REQUEST',
  USERS_UPDATE_SUCCESS = 'users/USERS_UPDATE_SUCCESS',
  USERS_UPDATE_FAILURE = 'users/USERS_UPDATE_FAILURE',

  USERS_REMOVE_REQUEST = 'users/USERS_REMOVE_REQUEST',
  USERS_REMOVE_SUCCESS = 'users/USERS_REMOVE_SUCCESS',
  USERS_REMOVE_FAILURE = 'users/USERS_REMOVE_FAILURE',

  USER_SET_ADD_DIALOG_OPEN_STATUS = 'users/USER_SET_ADD_DIALOG_OPEN_STATUS',
  USER_SET_EDIT_DIALOG_OPEN_STATUS = 'users/USER_SET_EDIT_DIALOG_OPEN_STATUS',
}